/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as NewIndexImport } from './routes/new/index'
import { Route as SSnippetIdImport } from './routes/s/$snippet-id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NewIndexRoute = NewIndexImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRoute,
} as any)

const SSnippetIdRoute = SSnippetIdImport.update({
  id: '/s/$snippet-id',
  path: '/s/$snippet-id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/s/$snippet-id': {
      id: '/s/$snippet-id'
      path: '/s/$snippet-id'
      fullPath: '/s/$snippet-id'
      preLoaderRoute: typeof SSnippetIdImport
      parentRoute: typeof rootRoute
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$snippet-id': typeof SSnippetIdRoute
  '/new': typeof NewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$snippet-id': typeof SSnippetIdRoute
  '/new': typeof NewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/s/$snippet-id': typeof SSnippetIdRoute
  '/new/': typeof NewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$snippet-id' | '/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$snippet-id' | '/new'
  id: '__root__' | '/' | '/s/$snippet-id' | '/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SSnippetIdRoute: typeof SSnippetIdRoute
  NewIndexRoute: typeof NewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SSnippetIdRoute: SSnippetIdRoute,
  NewIndexRoute: NewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/s/$snippet-id",
        "/new/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/s/$snippet-id": {
      "filePath": "s/$snippet-id.tsx"
    },
    "/new/": {
      "filePath": "new/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
